import { NameProfile, Ethnicity } from './types';

export const NAME_DICTIONARY: Record<string, NameProfile> = {
    // --- YORUBA ---
    'ade': { name: 'Ade', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'adebayo': { name: 'Adebayo', gender: 'Male', ethnicity: ['Yoruba'] },
    'adebola': { name: 'Adebola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'adedoyin': { name: 'Adedoyin', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'adewale': { name: 'Adewale', gender: 'Male', ethnicity: ['Yoruba'] },
    'abiodun': { name: 'Abiodun', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'ayomide': { name: 'Ayomide', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'boluwatife': { name: 'Boluwatife', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'damilola': { name: 'Damilola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'enitan': { name: 'Enitan', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'femi': { name: 'Femi', gender: 'Male', ethnicity: ['Yoruba'] },
    'funke': { name: 'Funke', gender: 'Female', ethnicity: ['Yoruba'] },
    'gbenga': { name: 'Gbenga', gender: 'Male', ethnicity: ['Yoruba'] },
    'ibukun': { name: 'Ibukun', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'ifunanya': { name: 'Ifunanya', gender: 'Female', ethnicity: ['Igbo'] }, // Mixed list, but categorized
    'kehind': { name: 'Kehinde', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'kemi': { name: 'Kemi', gender: 'Female', ethnicity: ['Yoruba'] },
    'kunle': { name: 'Kunle', gender: 'Male', ethnicity: ['Yoruba'] },
    'layomi': { name: 'Layomi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'mayowa': { name: 'Mayowa', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'nike': { name: 'Nike', gender: 'Female', ethnicity: ['Yoruba'] },
    'oluwaseun': { name: 'Oluwaseun', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'opeyemi': { name: 'Opeyemi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'seun': { name: 'Seun', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'temitope': { name: 'Temitope', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'tunde': { name: 'Tunde', gender: 'Male', ethnicity: ['Yoruba'] },
    'yemi': { name: 'Yemi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'abimbola': { name: 'Abimbola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'abisola': { name: 'Abisola', gender: 'Female', ethnicity: ['Yoruba'] },
    'adebisi': { name: 'Adebisi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'adekunle': { name: 'Adekunle', gender: 'Male', ethnicity: ['Yoruba'] },
    'adelani': { name: 'Adelani', gender: 'Male', ethnicity: ['Yoruba'] },
    'ademola': { name: 'Ademola', gender: 'Male', ethnicity: ['Yoruba'] },
    'adenike': { name: 'Adenike', gender: 'Female', ethnicity: ['Yoruba'] },
    'adeniyi': { name: 'Adeniyi', gender: 'Male', ethnicity: ['Yoruba'] },
    'adeola': { name: 'Adeola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'aderonke': { name: 'Aderonke', gender: 'Female', ethnicity: ['Yoruba'] },
    'adesola': { name: 'Adesola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'adetoun': { name: 'Adetoun', gender: 'Female', ethnicity: ['Yoruba'] },
    'adunni': { name: 'Adunni', gender: 'Female', ethnicity: ['Yoruba'] },
    'agboola': { name: 'Agboola', gender: 'Male', ethnicity: ['Yoruba'] },
    'ajibola': { name: 'Ajibola', gender: 'Male', ethnicity: ['Yoruba'] },
    'akintunde': { name: 'Akintunde', gender: 'Male', ethnicity: ['Yoruba'] },
    'alade': { name: 'Alade', gender: 'Male', ethnicity: ['Yoruba'] },
    'ara': { name: 'Ara', gender: 'Female', ethnicity: ['Yoruba'] },
    'aramide': { name: 'Aramide', gender: 'Female', ethnicity: ['Yoruba'] },
    'atanda': { name: 'Atanda', gender: 'Male', ethnicity: ['Yoruba'] },
    'awero': { name: 'Awero', gender: 'Female', ethnicity: ['Yoruba'] },
    'ayinde': { name: 'Ayinde', gender: 'Male', ethnicity: ['Yoruba'] },
    'ayobami': { name: 'Ayobami', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'ayodele': { name: 'Ayodele', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'ayodeji': { name: 'Ayodeji', gender: 'Male', ethnicity: ['Yoruba'] },
    'ayotunde': { name: 'Ayotunde', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'babatunde': { name: 'Babatunde', gender: 'Male', ethnicity: ['Yoruba'] },
    'bankole': { name: 'Bankole', gender: 'Male', ethnicity: ['Yoruba'] },
    'bayode': { name: 'Bayode', gender: 'Male', ethnicity: ['Yoruba'] },
    'bidemi': { name: 'Bidemi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'biodun': { name: 'Biodun', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'bisola': { name: 'Bisola', gender: 'Female', ethnicity: ['Yoruba'] },
    'bolaji': { name: 'Bolaji', gender: 'Male', ethnicity: ['Yoruba'] },
    'bolanle': { name: 'Bolanle', gender: 'Female', ethnicity: ['Yoruba'] },
    'bosede': { name: 'Bosede', gender: 'Female', ethnicity: ['Yoruba'] },
    'bukola': { name: 'Bukola', gender: 'Female', ethnicity: ['Yoruba'] },
    'busayo': { name: 'Busayo', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'damola': { name: 'Damola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'dayo': { name: 'Dayo', gender: 'Male', ethnicity: ['Yoruba'] },
    'ebun': { name: 'Ebun', gender: 'Female', ethnicity: ['Yoruba'] },
    'folake': { name: 'Folake', gender: 'Female', ethnicity: ['Yoruba'] },
    'folashade': { name: 'Folashade', gender: 'Female', ethnicity: ['Yoruba'] },
    'foluso': { name: 'Foluso', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'funmilayo': { name: 'Funmilayo', gender: 'Female', ethnicity: ['Yoruba'] },
    'funmilola': { name: 'Funmilola', gender: 'Female', ethnicity: ['Yoruba'] },
    'gbemisola': { name: 'Gbemisola', gender: 'Female', ethnicity: ['Yoruba'] },
    'idowu': { name: 'Idowu', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'ifeoluwa': { name: 'Ifeoluwa', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'ifetayo': { name: 'Ifetayo', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'ige': { name: 'Ige', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'iyabo': { name: 'Iyabo', gender: 'Female', ethnicity: ['Yoruba'] },
    'jide': { name: 'Jide', gender: 'Male', ethnicity: ['Yoruba'] },
    'jimoh': { name: 'Jimoh', gender: 'Male', ethnicity: ['Yoruba'] },
    'joke': { name: 'Joke', gender: 'Female', ethnicity: ['Yoruba'] },
    'jumoke': { name: 'Jumoke', gender: 'Female', ethnicity: ['Yoruba'] },
    'kayode': { name: 'Kayode', gender: 'Male', ethnicity: ['Yoruba'] },
    'kehinde': { name: 'Kehinde', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'kola': { name: 'Kola', gender: 'Male', ethnicity: ['Yoruba'] },
    'kolawole': { name: 'Kolawole', gender: 'Male', ethnicity: ['Yoruba'] },
    'kudirat': { name: 'Kudirat', gender: 'Female', ethnicity: ['Yoruba'] },
    'lanre': { name: 'Lanre', gender: 'Male', ethnicity: ['Yoruba'] },
    'lateef': { name: 'Lateef', gender: 'Male', ethnicity: ['Yoruba'] },
    'lekun': { name: 'Lekun', gender: 'Male', ethnicity: ['Yoruba'] },
    'mobolaji': { name: 'Mobolaji', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'modupe': { name: 'Modupe', gender: 'Female', ethnicity: ['Yoruba'] },
    'mojisola': { name: 'Mojisola', gender: 'Female', ethnicity: ['Yoruba'] },
    'monisola': { name: 'Monisola', gender: 'Female', ethnicity: ['Yoruba'] },
    'morayo': { name: 'Morayo', gender: 'Female', ethnicity: ['Yoruba'] },
    'mosunmola': { name: 'Mosunmola', gender: 'Female', ethnicity: ['Yoruba'] },
    'motunrayo': { name: 'Motunrayo', gender: 'Female', ethnicity: ['Yoruba'] },
    'muyiwa': { name: 'Muyiwa', gender: 'Male', ethnicity: ['Yoruba'] },
    'nifemi': { name: 'Nifemi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'niyi': { name: 'Niyi', gender: 'Male', ethnicity: ['Yoruba'] },
    'olabisi': { name: 'Olabisi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'oladele': { name: 'Oladele', gender: 'Male', ethnicity: ['Yoruba'] },
    'oladipo': { name: 'Oladipo', gender: 'Male', ethnicity: ['Yoruba'] },
    'olajide': { name: 'Olajide', gender: 'Male', ethnicity: ['Yoruba'] },
    'olamilekan': { name: 'Olamilekan', gender: 'Male', ethnicity: ['Yoruba'] },
    'olamide': { name: 'Olamide', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'olanrewaju': { name: 'Olanrewaju', gender: 'Male', ethnicity: ['Yoruba'] },
    'olanshile': { name: 'Olanshile', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'olapeju': { name: 'Olapeju', gender: 'Female', ethnicity: ['Yoruba'] },
    'olumide': { name: 'Olumide', gender: 'Male', ethnicity: ['Yoruba'] },
    'olusegun': { name: 'Olusegun', gender: 'Male', ethnicity: ['Yoruba'] },
    'olusola': { name: 'Olusola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'olutunde': { name: 'Olutunde', gender: 'Male', ethnicity: ['Yoruba'] },
    'oluwabusayo': { name: 'Oluwabusayo', gender: 'Female', ethnicity: ['Yoruba'] },
    'oluwafemi': { name: 'Oluwafemi', gender: 'Male', ethnicity: ['Yoruba'] },
    'oluwakemi': { name: 'Oluwakemi', gender: 'Female', ethnicity: ['Yoruba'] },
    'oluwanifemi': { name: 'Oluwanifemi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'oluwatobiloba': { name: 'Oluwatobiloba', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'oluwatoyin': { name: 'Oluwatoyin', gender: 'Female', ethnicity: ['Yoruba'] },
    'omobolanle': { name: 'Omobolanle', gender: 'Female', ethnicity: ['Yoruba'] },
    'omolara': { name: 'Omolara', gender: 'Female', ethnicity: ['Yoruba'] },
    'omowunmi': { name: 'Omowunmi', gender: 'Female', ethnicity: ['Yoruba'] },
    'oreoluwa': { name: 'Oreoluwa', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'oyindamola': { name: 'Oyindamola', gender: 'Female', ethnicity: ['Yoruba'] },
    'pelumi': { name: 'Pelumi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'rotimi': { name: 'Rotimi', gender: 'Male', ethnicity: ['Yoruba'] },
    'segun': { name: 'Segun', gender: 'Male', ethnicity: ['Yoruba'] },
    'seyi': { name: 'Seyi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'shade': { name: 'Shade', gender: 'Female', ethnicity: ['Yoruba'] },
    'shola': { name: 'Shola', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'simisola': { name: 'Simisola', gender: 'Female', ethnicity: ['Yoruba'] },
    'taiw': { name: 'Taiwo', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'taiwo': { name: 'Taiwo', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'temidayo': { name: 'Temidayo', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'temiloluwa': { name: 'Temiloluwa', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'titilayo': { name: 'Titilayo', gender: 'Female', ethnicity: ['Yoruba'] },
    'tobi': { name: 'Tobi', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'tolulope': { name: 'Tolulope', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'tope': { name: 'Tope', gender: 'Unisex', ethnicity: ['Yoruba'] },
    'toyin': { name: 'Toyin', gender: 'Female', ethnicity: ['Yoruba'] },
    'wasiu': { name: 'Wasiu', gender: 'Male', ethnicity: ['Yoruba'] },
    'yetunde': { name: 'Yetunde', gender: 'Female', ethnicity: ['Yoruba'] },
    'yewande': { name: 'Yewande', gender: 'Female', ethnicity: ['Yoruba'] },
    'yinka': { name: 'Yinka', gender: 'Unisex', ethnicity: ['Yoruba'] },

    // --- IGBO ---
    'ada': { name: 'Ada', gender: 'Female', ethnicity: ['Igbo'] },
    'amaka': { name: 'Amaka', gender: 'Female', ethnicity: ['Igbo'] },
    'chibuike': { name: 'Chibuike', gender: 'Male', ethnicity: ['Igbo'] },
    'chidiebere': { name: 'Chidiebere', gender: 'Unisex', ethnicity: ['Igbo'] },
    'chidinma': { name: 'Chidinma', gender: 'Female', ethnicity: ['Igbo'] },
    'chigozie': { name: 'Chigozie', gender: 'Unisex', ethnicity: ['Igbo'] },
    'chika': { name: 'Chika', gender: 'Unisex', ethnicity: ['Igbo'] },
    'chinedu': { name: 'Chinedu', gender: 'Male', ethnicity: ['Igbo'] },
    'chinonso': { name: 'Chinonso', gender: 'Unisex', ethnicity: ['Igbo'] },
    'chisom': { name: 'Chisom', gender: 'Unisex', ethnicity: ['Igbo'] },
    'chukwudi': { name: 'Chukwudi', gender: 'Male', ethnicity: ['Igbo'] },
    'ebuka': { name: 'Ebuka', gender: 'Male', ethnicity: ['Igbo'] },
    'emeka': { name: 'Emeka', gender: 'Male', ethnicity: ['Igbo'] },
    'ifeanyi': { name: 'Ifeanyi', gender: 'Male', ethnicity: ['Igbo'] },
    'keju': { name: 'Keju', gender: 'Female', ethnicity: ['Igbo'] }, // Rare but exists
    'ngozi': { name: 'Ngozi', gender: 'Female', ethnicity: ['Igbo'] },
    'nkechi': { name: 'Nkechi', gender: 'Female', ethnicity: ['Igbo'] },
    'obi': { name: 'Obi', gender: 'Male', ethnicity: ['Igbo'] },
    'okey': { name: 'Okey', gender: 'Male', ethnicity: ['Igbo'] },
    'onyeka': { name: 'Onyeka', gender: 'Unisex', ethnicity: ['Igbo'] },
    'uche': { name: 'Uche', gender: 'Unisex', ethnicity: ['Igbo'] },
    'adaeze': { name: 'Adaeze', gender: 'Female', ethnicity: ['Igbo'] },
    'adanna': { name: 'Adanna', gender: 'Female', ethnicity: ['Igbo'] },
    'adannaya': { name: 'Adannaya', gender: 'Female', ethnicity: ['Igbo'] },
    'aku': { name: 'Aku', gender: 'Female', ethnicity: ['Igbo'] },
    'akunna': { name: 'Akunna', gender: 'Female', ethnicity: ['Igbo'] },
    'amarachi': { name: 'Amarachi', gender: 'Female', ethnicity: ['Igbo'] },
    'azubuike': { name: 'Azubuike', gender: 'Male', ethnicity: ['Igbo'] },
    'azuka': { name: 'Azuka', gender: 'Unisex', ethnicity: ['Igbo'] },
    'chiamaka': { name: 'Chiamaka', gender: 'Female', ethnicity: ['Igbo'] },
    'chibueze': { name: 'Chibueze', gender: 'Male', ethnicity: ['Igbo'] },
    'chibuzor': { name: 'Chibuzor', gender: 'Unisex', ethnicity: ['Igbo'] },
    'chidi': { name: 'Chidi', gender: 'Male', ethnicity: ['Igbo'] },
    'chidimma': { name: 'Chidimma', gender: 'Female', ethnicity: ['Igbo'] },
    'chidubem': { name: 'Chidubem', gender: 'Male', ethnicity: ['Igbo'] },
    'chiemeka': { name: 'Chiemeka', gender: 'Male', ethnicity: ['Igbo'] },
    'chijindu': { name: 'Chijindu', gender: 'Male', ethnicity: ['Igbo'] },
    'chima': { name: 'Chima', gender: 'Male', ethnicity: ['Igbo'] },
    'chinwe': { name: 'Chinwe', gender: 'Female', ethnicity: ['Igbo'] },
    'chinyere': { name: 'Chinyere', gender: 'Female', ethnicity: ['Igbo'] },
    'chioma': { name: 'Chioma', gender: 'Female', ethnicity: ['Igbo'] },
    'chukwuka': { name: 'Chukwuka', gender: 'Male', ethnicity: ['Igbo'] },
    'chukwuma': { name: 'Chukwuma', gender: 'Male', ethnicity: ['Igbo'] },
    'daberechi': { name: 'Daberechi', gender: 'Unisex', ethnicity: ['Igbo'] },
    'daluchi': { name: 'Daluchi', gender: 'Unisex', ethnicity: ['Igbo'] },
    'ebube': { name: 'Ebube', gender: 'Unisex', ethnicity: ['Igbo'] },
    'ebele': { name: 'Ebele', gender: 'Female', ethnicity: ['Igbo'] },
    'ejike': { name: 'Ejike', gender: 'Male', ethnicity: ['Igbo'] },
    'eke': { name: 'Eke', gender: 'Male', ethnicity: ['Igbo'] },
    'ekene': { name: 'Ekene', gender: 'Unisex', ethnicity: ['Igbo'] },
    'ekwe': { name: 'Ekwe', gender: 'Male', ethnicity: ['Igbo'] },
    'favour': { name: 'Favour', gender: 'Female', ethnicity: ['Igbo'] }, // English but very common in Igbo
    'fechi': { name: 'Fechi', gender: 'Unisex', ethnicity: ['Igbo'] },
    'ginika': { name: 'Ginika', gender: 'Female', ethnicity: ['Igbo'] },
    'goodluck': { name: 'Goodluck', gender: 'Male', ethnicity: ['Igbo'] },
    'ifeoma': { name: 'Ifeoma', gender: 'Female', ethnicity: ['Igbo'] },
    'igwe': { name: 'Igwe', gender: 'Male', ethnicity: ['Igbo'] },
    'ikechukwu': { name: 'Ikechukwu', gender: 'Male', ethnicity: ['Igbo'] },
    'ikemefuna': { name: 'Ikemefuna', gender: 'Male', ethnicity: ['Igbo'] },
    'jeoma': { name: 'Ijeoma', gender: 'Female', ethnicity: ['Igbo'] },
    'ijeoma': { name: 'Ijeoma', gender: 'Female', ethnicity: ['Igbo'] },
    'kalu': { name: 'Kalu', gender: 'Male', ethnicity: ['Igbo'] },
    'kanayo': { name: 'Kanayo', gender: 'Male', ethnicity: ['Igbo'] },
    'kelechi': { name: 'Kelechi', gender: 'Unisex', ethnicity: ['Igbo'] },
    'kenechukwu': { name: 'Kenechukwu', gender: 'Male', ethnicity: ['Igbo'] },
    'lotanna': { name: 'Lotanna', gender: 'Male', ethnicity: ['Igbo'] },
    'madu': { name: 'Madu', gender: 'Male', ethnicity: ['Igbo'] },
    'makuochukwu': { name: 'Makuochukwu', gender: 'Unisex', ethnicity: ['Igbo'] },
    'mesoma': { name: 'Mesoma', gender: 'Female', ethnicity: ['Igbo'] },
    'ndidi': { name: 'Ndidi', gender: 'Female', ethnicity: ['Igbo'] },
    'ndubuisi': { name: 'Ndubuisi', gender: 'Male', ethnicity: ['Igbo'] },
    'nnamdi': { name: 'Nnamdi', gender: 'Male', ethnicity: ['Igbo'] },
    'nneka': { name: 'Nneka', gender: 'Female', ethnicity: ['Igbo'] },
    'nnenna': { name: 'Nnenna', gender: 'Female', ethnicity: ['Igbo'] },
    'nwabueze': { name: 'Nwabueze', gender: 'Male', ethnicity: ['Igbo'] },
    'nwakaego': { name: 'Nwakaego', gender: 'Female', ethnicity: ['Igbo'] },
    'nwankwo': { name: 'Nwankwo', gender: 'Male', ethnicity: ['Igbo'] },
    'obinna': { name: 'Obinna', gender: 'Male', ethnicity: ['Igbo'] },
    'obiora': { name: 'Obiora', gender: 'Male', ethnicity: ['Igbo'] },
    'ogbonna': { name: 'Ogbonna', gender: 'Male', ethnicity: ['Igbo'] },
    'ogechi': { name: 'Ogechi', gender: 'Female', ethnicity: ['Igbo'] },
    'okeke': { name: 'Okeke', gender: 'Male', ethnicity: ['Igbo'] },
    'okonkwo': { name: 'Okonkwo', gender: 'Male', ethnicity: ['Igbo'] },
    'okoro': { name: 'Okoro', gender: 'Male', ethnicity: ['Igbo'] },
    'oluchi': { name: 'Oluchi', gender: 'Female', ethnicity: ['Igbo'] },
    'onye': { name: 'Onye', gender: 'Male', ethnicity: ['Igbo'] },
    'onyinye': { name: 'Onyinye', gender: 'Female', ethnicity: ['Igbo'] },
    'onyinyechi': { name: 'Onyinyechi', gender: 'Female', ethnicity: ['Igbo'] },
    'osita': { name: 'Osita', gender: 'Male', ethnicity: ['Igbo'] },
    'somtochukwu': { name: 'Somtochukwu', gender: 'Unisex', ethnicity: ['Igbo'] },
    'tobechukwu': { name: 'Tobechukwu', gender: 'Male', ethnicity: ['Igbo'] },
    'ucheckwu': { name: 'Uchechukwu', gender: 'Unisex', ethnicity: ['Igbo'] },
    'uchechukwu': { name: 'Uchechukwu', gender: 'Unisex', ethnicity: ['Igbo'] },
    'uchenna': { name: 'Uchenna', gender: 'Unisex', ethnicity: ['Igbo'] },
    'udoka': { name: 'Udoka', gender: 'Unisex', ethnicity: ['Igbo'] },
    'ugonna': { name: 'Ugonna', gender: 'Male', ethnicity: ['Igbo'] },
    'uwan': { name: 'Uwan', gender: 'Female', ethnicity: ['Igbo'] },
    'uzoma': { name: 'Uzoma', gender: 'Unisex', ethnicity: ['Igbo'] },
    'victor': { name: 'Victor', gender: 'Male', ethnicity: ['Igbo'] }, // Common
    'victoria': { name: 'Victoria', gender: 'Female', ethnicity: ['Igbo'] }, // Common

    // --- HAUSA ---
    'abdul': { name: 'Abdul', gender: 'Male', ethnicity: ['Hausa'] },
    'aisha': { name: 'Aisha', gender: 'Female', ethnicity: ['Hausa'] },
    'aliyu': { name: 'Aliyu', gender: 'Male', ethnicity: ['Hausa'] },
    'aminu': { name: 'Aminu', gender: 'Male', ethnicity: ['Hausa'] },
    'bello': { name: 'Bello', gender: 'Male', ethnicity: ['Hausa'] },
    'fatima': { name: 'Fatima', gender: 'Female', ethnicity: ['Hausa'] },
    'hassan': { name: 'Hassan', gender: 'Male', ethnicity: ['Hausa'] },
    'hussaini': { name: 'Hussaini', gender: 'Male', ethnicity: ['Hausa'] },
    'ibrahim': { name: 'Ibrahim', gender: 'Male', ethnicity: ['Hausa'] },
    'maryam': { name: 'Maryam', gender: 'Female', ethnicity: ['Hausa'] }, // Also common in others, but very Hausa
    'mohammed': { name: 'Mohammed', gender: 'Male', ethnicity: ['Hausa'] },
    'musa': { name: 'Musa', gender: 'Male', ethnicity: ['Hausa'] },
    'sani': { name: 'Sani', gender: 'Male', ethnicity: ['Hausa'] },
    'umar': { name: 'Umar', gender: 'Male', ethnicity: ['Hausa'] },
    'usman': { name: 'Usman', gender: 'Male', ethnicity: ['Hausa'] },
    'zainab': { name: 'Zainab', gender: 'Female', ethnicity: ['Hausa'] },
    'abubakar': { name: 'Abubakar', gender: 'Male', ethnicity: ['Hausa'] },
    'adamu': { name: 'Adamu', gender: 'Male', ethnicity: ['Hausa'] },
    'ahmed': { name: 'Ahmed', gender: 'Male', ethnicity: ['Hausa'] },
    'amina': { name: 'Amina', gender: 'Female', ethnicity: ['Hausa'] },
    'bashir': { name: 'Bashir', gender: 'Male', ethnicity: ['Hausa'] },
    'bilkisu': { name: 'Bilkisu', gender: 'Female', ethnicity: ['Hausa'] },
    'danladi': { name: 'Danladi', gender: 'Male', ethnicity: ['Hausa'] },
    'danjuma': { name: 'Danjuma', gender: 'Male', ethnicity: ['Hausa'] },
    'faruk': { name: 'Faruk', gender: 'Male', ethnicity: ['Hausa'] },
    'fati': { name: 'Fati', gender: 'Female', ethnicity: ['Hausa'] },
    'gamb': { name: 'Gambo', gender: 'Unisex', ethnicity: ['Hausa'] },
    'gambo': { name: 'Gambo', gender: 'Unisex', ethnicity: ['Hausa'] },
    'garba': { name: 'Garba', gender: 'Male', ethnicity: ['Hausa'] },
    'habiba': { name: 'Habiba', gender: 'Female', ethnicity: ['Hausa'] },
    'hadiza': { name: 'Hadiza', gender: 'Female', ethnicity: ['Hausa'] },
    'hafsat': { name: 'Hafsat', gender: 'Female', ethnicity: ['Hausa'] },
    'halima': { name: 'Halima', gender: 'Female', ethnicity: ['Hausa'] },
    'hamza': { name: 'Hamza', gender: 'Male', ethnicity: ['Hausa'] },
    'haruna': { name: 'Haruna', gender: 'Male', ethnicity: ['Hausa'] },
    'hauwa': { name: 'Hauwa', gender: 'Female', ethnicity: ['Hausa'] },
    'idris': { name: 'Idris', gender: 'Male', ethnicity: ['Hausa'] },
    'isa': { name: 'Isa', gender: 'Male', ethnicity: ['Hausa'] },
    'ismail': { name: 'Ismail', gender: 'Male', ethnicity: ['Hausa'] },
    'jamilu': { name: 'Jamilu', gender: 'Male', ethnicity: ['Hausa'] },
    'jibril': { name: 'Jibril', gender: 'Male', ethnicity: ['Hausa'] },
    'kabiru': { name: 'Kabiru', gender: 'Male', ethnicity: ['Hausa'] },
    'kadijat': { name: 'Kadijat', gender: 'Female', ethnicity: ['Hausa'] },
    'khadija': { name: 'Khadija', gender: 'Female', ethnicity: ['Hausa'] },
    'lawal': { name: 'Lawal', gender: 'Male', ethnicity: ['Hausa'] },
    'maimuna': { name: 'Maimuna', gender: 'Female', ethnicity: ['Hausa'] },
    'mansur': { name: 'Mansur', gender: 'Male', ethnicity: ['Hausa'] },
    'mustapha': { name: 'Mustapha', gender: 'Male', ethnicity: ['Hausa'] },
    'nafisa': { name: 'Nafisa', gender: 'Female', ethnicity: ['Hausa'] },
    'nasiru': { name: 'Nasiru', gender: 'Male', ethnicity: ['Hausa'] },
    'rabiu': { name: 'Rabiu', gender: 'Male', ethnicity: ['Hausa'] },
    'rahama': { name: 'Rahama', gender: 'Female', ethnicity: ['Hausa'] },
    'rashida': { name: 'Rashida', gender: 'Female', ethnicity: ['Hausa'] },
    'rukuyya': { name: 'Rukuyya', gender: 'Female', ethnicity: ['Hausa'] },
    'safiya': { name: 'Safiya', gender: 'Female', ethnicity: ['Hausa'] },
    'salisu': { name: 'Salisu', gender: 'Male', ethnicity: ['Hausa'] },
    'shehu': { name: 'Shehu', gender: 'Male', ethnicity: ['Hausa'] },
    'suleiman': { name: 'Suleiman', gender: 'Male', ethnicity: ['Hausa'] },
    'tanko': { name: 'Tanko', gender: 'Male', ethnicity: ['Hausa'] },
    'yahuza': { name: 'Yahuza', gender: 'Male', ethnicity: ['Hausa'] },
    'yakubu': { name: 'Yakubu', gender: 'Male', ethnicity: ['Hausa'] },
    'yusuf': { name: 'Yusuf', gender: 'Male', ethnicity: ['Hausa'] },

    // --- EDO ---
    'adesuwa': { name: 'Adesuwa', gender: 'Female', ethnicity: ['Edo'] },
    'efosa': { name: 'Efosa', gender: 'Male', ethnicity: ['Edo'] },
    'ehis': { name: 'Ehis', gender: 'Male', ethnicity: ['Edo'] },
    'nosa': { name: 'Nosa', gender: 'Male', ethnicity: ['Edo'] },
    'osas': { name: 'Osas', gender: 'Unisex', ethnicity: ['Edo'] },
    'osaze': { name: 'Osaze', gender: 'Male', ethnicity: ['Edo'] },
    'aisosa': { name: 'Aisosa', gender: 'Unisex', ethnicity: ['Edo'] },
    'amenze': { name: 'Amenze', gender: 'Female', ethnicity: ['Edo'] },
    'eghosa': { name: 'Eghosa', gender: 'Male', ethnicity: ['Edo'] },
    'ehigiator': { name: 'Ehigiator', gender: 'Male', ethnicity: ['Edo'] },
    'ehizogie': { name: 'Ehizogie', gender: 'Unisex', ethnicity: ['Edo'] },
    'ekpen': { name: 'Ekpen', gender: 'Unisex', ethnicity: ['Edo'] },
    'enoma': { name: 'Enoma', gender: 'Male', ethnicity: ['Edo'] },
    'esosa': { name: 'Esosa', gender: 'Unisex', ethnicity: ['Edo'] },
    'etinosa': { name: 'Etinosa', gender: 'Unisex', ethnicity: ['Edo'] },
    'idahosa': { name: 'Idahosa', gender: 'Male', ethnicity: ['Edo'] },
    'ighodaro': { name: 'Ighodaro', gender: 'Male', ethnicity: ['Edo'] },
    'isoken': { name: 'Isoken', gender: 'Female', ethnicity: ['Edo'] },
    'ivie': { name: 'Ivie', gender: 'Female', ethnicity: ['Edo'] },
    'iyobosa': { name: 'Iyobosa', gender: 'Female', ethnicity: ['Edo'] },
    'nosakhare': { name: 'Nosakhare', gender: 'Male', ethnicity: ['Edo'] },
    'odion': { name: 'Odion', gender: 'Unisex', ethnicity: ['Edo'] },
    'ogbeide': { name: 'Ogbeide', gender: 'Male', ethnicity: ['Edo'] },
    'omoregie': { name: 'Omoregie', gender: 'Male', ethnicity: ['Edo'] },
    'osagie': { name: 'Osagie', gender: 'Male', ethnicity: ['Edo'] },
    'osahon': { name: 'Osahon', gender: 'Male', ethnicity: ['Edo'] },
    'osakpamwan': { name: 'Osakpamwan', gender: 'Male', ethnicity: ['Edo'] },
    'osamwonyi': { name: 'Osamwonyi', gender: 'Male', ethnicity: ['Edo'] },
    'osaro': { name: 'Osaro', gender: 'Male', ethnicity: ['Edo'] },
    'osasere': { name: 'Osasere', gender: 'Unisex', ethnicity: ['Edo'] },
    'osasu': { name: 'Osasu', gender: 'Unisex', ethnicity: ['Edo'] },
    'osayande': { name: 'Osayande', gender: 'Male', ethnicity: ['Edo'] },
    'osayimwen': { name: 'Osayimwen', gender: 'Unisex', ethnicity: ['Edo'] },
    'osazuwa': { name: 'Osazuwa', gender: 'Male', ethnicity: ['Edo'] },
    'ose': { name: 'Ose', gender: 'Unisex', ethnicity: ['Edo'] },
    'osose': { name: 'Osose', gender: 'Female', ethnicity: ['Edo'] },
    'uwagboe': { name: 'Uwagboe', gender: 'Male', ethnicity: ['Edo'] },
    'uyi': { name: 'Uyi', gender: 'Unisex', ethnicity: ['Edo'] },
    'uyiosa': { name: 'Uyiosa', gender: 'Unisex', ethnicity: ['Edo'] },

    // --- EFIK/IBIBIO ---
    'edidiong': { name: 'Edidiong', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'emem': { name: 'Emem', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'idara': { name: 'Idara', gender: 'Female', ethnicity: ['Efik', 'Ibibio'] },
    'ini': { name: 'Ini', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'mfom': { name: 'Mfon', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'ubong': { name: 'Ubong', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'abasi': { name: 'Abasi', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'akan': { name: 'Akan', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'anietie': { name: 'Anietie', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'bassey': { name: 'Bassey', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'edem': { name: 'Edem', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'edet': { name: 'Edet', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'effiong': { name: 'Effiong', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'ekong': { name: 'Ekong', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'emmanuel': { name: 'Emmanuel', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] }, // Very common
    'eno': { name: 'Eno', gender: 'Female', ethnicity: ['Efik', 'Ibibio'] },
    'etim': { name: 'Etim', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'etuk': { name: 'Etuk', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'idongesit': { name: 'Idongesit', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'ima': { name: 'Ima', gender: 'Female', ethnicity: ['Efik', 'Ibibio'] },
    'imoh': { name: 'Imoh', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'iniiobong': { name: 'Iniobong', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'iniobong': { name: 'Iniobong', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'itoro': { name: 'Itoro', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'kokomma': { name: 'Kokomma', gender: 'Female', ethnicity: ['Efik', 'Ibibio'] },
    'kufre': { name: 'Kufre', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'mfome': { name: 'Mfoniso', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'mfoniso': { name: 'Mfoniso', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'nsikak': { name: 'Nsikak', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'obong': { name: 'Obong', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'okkon': { name: 'Okon', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'okon': { name: 'Okon', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'otobong': { name: 'Otobong', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'saviour': { name: 'Saviour', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'udeme': { name: 'Udeme', gender: 'Unisex', ethnicity: ['Efik', 'Ibibio'] },
    'udoh': { name: 'Udoh', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },
    'uwem': { name: 'Uwem', gender: 'Male', ethnicity: ['Efik', 'Ibibio'] },

    // --- URHOBO/ISOKO ---
    'akpevwe': { name: 'Akpevwe', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'brume': { name: 'Brume', gender: 'Male', ethnicity: ['Urhobo'] },
    'efe': { name: 'Efe', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'jiro': { name: 'Jiro', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'kevwe': { name: 'Kevwe', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'oghenekevwe': { name: 'Oghenekevwe', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'oghenerukevwe': { name: 'Oghenerukevwe', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'oghenetega': { name: 'Oghenetega', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'onome': { name: 'Onome', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'rukky': { name: 'Rukky', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'tega': { name: 'Tega', gender: 'Unisex', ethnicity: ['Urhobo'] },
    'tobore': { name: 'Tobore', gender: 'Unisex', ethnicity: ['Urhobo'] },
};

export const ETHNICITY_PATTERNS: { regex: RegExp; ethnicity: Ethnicity }[] = [
    { regex: /^(olu|ade|omi|ola|oye|ife|ibo)/i, ethnicity: 'Yoruba' },
    { regex: /^(chi|chuk|nwa|eke|obi|eze|okw|ugo)/i, ethnicity: 'Igbo' },
    { regex: /^(osa|ehi|omo)/i, ethnicity: 'Edo' },
    { regex: /^(abdul|moham|dan|mai|shehu|alhaji)/i, ethnicity: 'Hausa' },
    { regex: /^(edi|eti|obong|nsi|abasi)/i, ethnicity: 'Efik' } // Simplified
];

export const GENDER_HEURISTICS = {
    femaleSuffixes: [/a$/, /ye$/, /mi$/], // Very weak, need to be careful. 'Emeka' ends in 'a' but is male.
    malePrefixes: [/^olu/], // 'Olu' is often unisex but leans male in some compounds? No, Olu is God, very unisex.
    // Better heuristics:
    // Igbo: 'Chi' is unisex. 'Amaka' (Female).
    // Yoruba: 'Ade' is unisex.
};
